language: generic
dist: trusty
sudo: false

env:
  matrix:
    - EMACS_VERSION=emacs-24.4
    - EMACS_VERSION=emacs-24.5
    - EMACS_VERSION=emacs-25.1
    - EMACS_VERSION=emacs-25.2
    - EMACS_VERSION=emacs-git-snapshot
    - EMACS_VERSION=remacs-git-snapshot

matrix:
  allow_failures:
  - env: EMACS_VERSION=remacs-git-snapshot

before_script:
  # Install evm
  - git clone https://github.com/rejeep/evm.git ~/.evm
  - export PATH="$HOME/.evm/bin:$PATH"
  - evm config path /tmp
  - evm list
  # use this version of emacs for tests
  - evm install "${EMACS_VERSION}-travis" --use --skip
  - evm list
  - emacs --version
  # Install cask
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="$HOME/.cask/bin:$PATH"
  # Install elisp dependencies
  - cask install

script:
  - make compile
  - make test
